---
name: Build Windows Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"  # or the version you prefer

      - name: Install Poetry
        run: |
          pip install poetry
          poetry install

      - name: Build Executable
        run: |
          poetry run pyinstaller windows_exe.spec

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dwg-converter
          path: dist/
